apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: nexus-logistics
type: Opaque
data:
  # Base64 encoded values: echo -n 'value' | base64
  POSTGRES_USER: bmV4dXM= # nexus
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password
