apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus-logistics

resources:
  - namespace.yaml
  - configmaps/app-config.yaml
  - secrets/db-credentials.yaml
  - deployments/ingestion.yaml
  - deployments/tracking.yaml
  - deployments/route.yaml
  - deployments/frontend.yaml
  - services/ingestion-svc.yaml
  - services/tracking-svc.yaml
  - services/route-svc.yaml
  - services/frontend-svc.yaml
  - hpa/tracking-hpa.yaml
  - gateway/ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: nexus-logistics
