apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: nexus-logistics
data:
  KAFKA_BROKERS: "kafka:29092"
  REDIS_HOST: "redis"
  POSTGRES_HOST: "postgres"
  POSTGRES_DB: "nexus_logistics"
  NEXT_PUBLIC_API_URL: "http://gateway"
