apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-ingress
  namespace: nexus-logistics
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api/tracking(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: tracking-service
                port:
                  number: 3000
          - path: /api/routes(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: route-service
                port:
                  number: 8080
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: frontend
                port:
                  number: 80
