apiVersion: v1
kind: Service
metadata:
  name: route-service
  namespace: nexus-logistics
spec:
  type: ClusterIP
  selector:
    app: route-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
