apiVersion: v1
kind: Service
metadata:
  name: tracking-service
  namespace: nexus-logistics
spec:
  type: ClusterIP
  selector:
    app: tracking-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
